sudo: false
language: rust
rust:
  - nightly
addons:
  apt:
    packages:
      - nasm
os:
  - linux
before_install:
    - if [ `uname` = "Darwin" ]; then
        brew tap altkatz/homebrew-gcc_cross_compilers;
        brew update;
        brew unlink gcc;
        brew install i386-elf-binutils i386-elf-gcc nasm;
      fi
script:
  - make clean
  - make all -j
notifications:
  email: false
  webhooks: http://37.139.9.28:54863/travis
#branches:
#  only:
#    - auto
